### ISSUE TITLE
Improper "lru" import

### ISSUE THREAD

**Issue by ghost** [kz26/gohls#1]
The LRU import prevents the package from being go-gettable, or even buildable:

import "lru" // https://github.com/golang/groupcache/blob/master/lru/lru.go

**Comment by kz26** [comment]
It should build if you download and place `lru.go` alongside `main.go`. I'll probably include a copy in the repo in the future for convenience, since it seems space-inefficient to have users `go get` all of groupcache just to use one component.

**Comment by ghost** [comment]
Why not change the import to:

```
import "github.com/golang/groupcache/lru"
```

**Comment by kz26** [comment]
Good call, I didn't even realize that was possible. Thanks and fixed.
