### ISSUE TITLE
when files more than 1024

### ISSUE THREAD

**Issue by ilgyyymy** [kz26/gohls#9]
when we use this app to down load a movie which split as ts more than 1024,it won~t work,perhaps some parameter is limit 1024,can fix this bug in your next version?

**Comment by kz26** [comment]
Hi, I'm not quite sure what you're asking - are you having issues with creating a torrent with more than 1024 files?

**Comment by ilgyyymy** [comment]
是的，用您的软件在下载大于1024个ts分片时，会出现问题，建议您检查一下代码中关于默认分片个数限制的部分

**Comment by kz26** [comment]
You can modify the size of the cache and recompile to accomodate more than 1024: https://github.com/kz26/gohls/blob/master/main.go#L86
